### PR TITLE
Change README.md in update1 that will be merged into main branch

### PR DESCRIPTION
**Pull request by tatsuya-sano**
Please review this document.

### CODE REVIEW

**Review by tatsuya-sano-reviwer — APPROVED** [review]
Looks like there is no matter.

**Review by tatsuya-sano-reviwer — DISMISSED** [review]
OK

**Comment by tatsuya-sano** [comment]
Please review this document again

**Review by tatsuya-sano-reviwer — APPROVED** [review]
OK

**Pull request merged**
